#!/bin/bash

options=(
  style=round
  width=8.0 # Increased width for better visibility
  hidpi=on
  active_color=0xffb347ff
  inactive_color=0xff585b70
  blacklist=DeskMinder,sketchybar
)

borders "${options[@]}"
