#!/bin/bash
# Flags writes to build artifacts, binary files, and dependency directories and
# asks the user to confirm instead of hard-blocking.
# PreToolUse hook for Edit|Write operations. Does NOT inspect file size despite
# the original filename ("warn-large-files.sh") — that name was historical, the
# script always operated on paths + extensions. Renamed 2026-05-24.
# Emits an interactive "ask" decision (exit 0). NOTE: JSON permissionDecision is
# only honored on exit 0; exit 2 hard-blocks and the JSON is ignored.

PERMISSION_MODE=""

# emit_guard "<reason>": ask a human in interactive default mode; hard-deny in any
# autonomous mode where a hook "ask" would be auto-resolved to allow.
emit_guard() {
  local reason="${1//\"/\\\"}" decision
  if [ "$PERMISSION_MODE" = "default" ]; then
    decision="ask"
  else
    decision="deny"
    reason="$reason [auto-mode: blocked — rerun interactively to confirm]"
  fi
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"$decision\",\"permissionDecisionReason\":\"$reason\"}}"
  exit 0
}

# Requires jq for JSON parsing. Fail closed (deny) if missing.
if ! command -v jq >/dev/null 2>&1; then
  emit_guard "jq is required for file protection hooks but is not installed."
fi

INPUT=$(cat)
PERMISSION_MODE=$(echo "$INPUT" | jq -r '.permission_mode // ""')
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Block dependency and build directories
case "$FILE_PATH" in
  node_modules/*|*/node_modules/*)
    REASON="Cannot write into node_modules/. Install dependencies via package manager instead." ;;
  vendor/*|*/vendor/*)
    REASON="Cannot write into vendor/. Use dependency manager instead." ;;
  dist/*|*/dist/*|build/*|*/build/*|.next/*|*/.next/*)
    REASON="Cannot write into build output directories. These are generated by the build process." ;;
  __pycache__/*|*/__pycache__/*)
    REASON="Cannot write into __pycache__/. These are generated by Python." ;;
  .venv/*|*/.venv/*|venv/*|*/venv/*)
    REASON="Cannot write into virtual environment directories." ;;
  *)
    REASON="" ;;
esac

if [ -n "$REASON" ]; then
  emit_guard "$REASON"
fi

# Block binary and archive file extensions
BASENAME=$(basename "$FILE_PATH")
case "$BASENAME" in
  *.wasm|*.so|*.dylib|*.dll|*.exe|*.o|*.a)
    REASON="Cannot write binary files. These should be compiled, not hand-written." ;;
  *.zip|*.tar|*.tar.gz|*.tar.bz2|*.tgz|*.rar|*.7z)
    REASON="Cannot write archive files." ;;
  *.mp4|*.mov|*.avi|*.mkv|*.mp3|*.wav|*.flac)
    REASON="Cannot write media files. Add these manually outside Claude Code." ;;
  *.pyc|*.pyo|*.class)
    REASON="Cannot write compiled bytecode files." ;;
esac

if [ -n "$REASON" ]; then
  emit_guard "$REASON"
fi

exit 0
